### PR TITLE
Refactor SQLiteDataConverter and DataConverter

### PR DESCRIPTION
**Pull request by asogaard**
Working on #11 as well as a general refactor and simplification of these two classes. Creating a PR draft, as the work is still underway, in order to be able to start having a discussion.

### CODE REVIEW

**Comment by asogaard** [comment]
Hi @RasmusOrsoe,
The PR now goes some way towards what it says on the tin (refactoring the two classes), and perhaps most importantly it addresses issue #11. To avoid ballooning this PR any further I propose not making any more changes (except for requests during review) before we have had a chance to discuss and merge this first.

**Review by RasmusOrsoe — COMMENTED** [review]
Hi! Looks nice. 

I can see that the i3/gcd file search has changed quite  a bit and I understand very little of the new code. Are we 100% sure its identical?

If so, lets merge.

Rasmus

**Comment by asogaard** [comment]
Thanks for reviewing, @RasmusOrsoe! I have checked, and the two should agree, but I will prepare a double-check just to be sure.

**Comment by asogaard** [comment]
For reference, the new function(s) make two changes:
* They explicitly ignore files that don't resemble I3 or GCD files.
* Return all I3 files in a certain directory, regardless of depth.

**Review by RasmusOrsoe — APPROVED** [review]
i3/gcd finder tested and works.

**Pull request merged**
